openapi: 3.0.0
info:
  title: API de Productos
  version: 1.0.0
  description: API que gestiona productos, testers y tests

servers:
  - url: http://localhost:3000

paths: {}
components:
  schemas:
    Size:
      type: string
      description: Talla del producto
